export const USER_ID = 'USER_ID'
export const USER = 'USER'
export const ERROR_STATE = 'ERROR_STATE'
export const IS_AUTH = 'IS_AUTH'
export const IS_LOGIN = 'IS_LOGIN'
export const LOGIN_TYPE = 'LOGIN_TYPE'