server:
 port: 8001
spring:
 datasource:
  url: jdbc:h2:file:~/sc
  username: sa
  password: 
  driver-class-name: org.h2.Driver
 h2:
  console:
   enabled: true
 jpa:
  database: H2
  show-sql: true
  defer-datasource-initialization: true 
  hibernate:
   ddl-auto: create #개발
   #ddl-auto: validate
  properties:
   hibernate:
    format_sql: true
jwt:
 secret: KAKAOPAYSERVICECENTERDEMO

    

      
 
 
  
 
  
   
  
   